# Generated by Django 5.0.6 on 2024-08-03 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.salon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stylist',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stylists', to='api.salon'),
            preserve_default=False,
        ),
    ]
