# Generated by Django 5.0.7 on 2024-08-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_salon_alter_stylist_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
