# Generated by Django 5.0.7 on 2024-08-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_latitude_longitude_to_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
