# Generated by Django 5.0.7 on 2024-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_salon_alter_stylist_phone_and_more'),
        ('booking', '0002_remove_appointment_service_appointment_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='api.service'),
        ),
    ]
